### ISSUE TITLE
SSL error in browser

### ISSUE THREAD

**Issue by superfein** [amoser67/shopify_dev_utils#3]
Getting this error in Chrome:

```
This site can’t provide a secure connection
localhost sent an invalid response.
Try running Windows Network Diagnostics.
ERR_SSL_PROTOCOL_ERROR
```

Got a similar error in Firefox. 

Tried with a published theme and an unpublished theme with the `store_preview_url` set in the `.env` file for the unpublished theme.

Tried using a different port from 8080, tried 3000. Same results.

The application starts, auto-loads a browser tab with `https://locahost:8080` but the SSL error is immediate and no errors show up in the terminal.

shopify_dev_util v1.0.23
Node v13.8.0

**Comment by amoser67** [comment]
Just to clarify, your local host url is prefaced with https?

**Comment by amoser67** [comment]
Thinking it might be a websocket issue, it defines the websocket as:
`var socket = new WebSocket("ws://" + location.host + "/websocket");`
And I am wondering if the ws:// is messing with the paths for windows.  Looking into it.

**Comment by amoser67** [comment]
So I finally buckled down and setup a full windows dev env so I could check out what was going on.  Everything worked fine for me though, all the files were watched and uploaded properly, and my browser was refreshed automatically after each change.   If I change the url to say https://localhost:8000 instead of localhost:8000 then I get the exact error you described, so just make sure you arent prefacing it with https:// since you are just communicating locally.

**Comment by superfein** [comment]
Thanks @amoser67, without the `https://` it successfully opens a tab in the browser and connects to Shopify using the Preview URL. Unfortunately, no files are being uploaded to Shopify, despite the `Uploaded` message in the terminal. I'm going to open a separate issue.
