### ISSUE TITLE
Files not being uploaded to Shopify

### ISSUE THREAD

**Issue by superfein** [amoser67/shopify_dev_utils#4]
In my terminal, every time I save a file or asset, I receive the `Uploaded` message with the status code of `401`:

```
$ node run
[11:19:26] - Application -- ready
statusCode:  401
[11:22:30] - Uploaded -- assets/main.min.css.liquid
statusCode:  401
[11:23:55] - Uploaded -- layout/theme.liquid
statusCode:  401
[11:24:41] - Uploaded -- assets/main.min.css.liquid
statusCode:  401
[11:27:38] - Uploaded -- layout/theme.liquid
```

But none of these files are actually being uploaded to Shopify. I updated the `theme.liquid` file to include the new `main.min.css` asset_url, but the updated file never copied over the current `theme.liquid` file in Shopify.

In the `styles` directory, I created a `main.scss` file and a components sub-directory with mixins, functions etc. When saved this file successfully copies to the assets directory, and is renamed and minified to `main.min.css.liquid`. When I make changes to `main.scss` they correctly appear in `main.min.css.liquid`. But this asset never uploads to Shopify, despite the `Uploaded` message.

The browser refreshes after each file is saved, that looks good.

Just to confirm, I'm using an unpublished theme and using the Preview Url as the STORE_PREVIEW_URL in the `.env` file. The preview url looks like this: 
`36na71d6da3neqnx-32475414660.shopifypreview.com`

Not sure what's happening as there's no errors at all. Any ideas what might be happening here?

**Comment by amoser67** [comment]
Well, 401 is the unauthorized HTTP response code, so the request IS failing.  Since I dont receive this error on windows, I want to see if maybe something is off with your setup.  The preview url expires after two weeks, do you know if yours is satisfies that?  If that is taken care of, then double check that you have private_app_api_key:private_app_api_password as your AUTH environment variable, and that the private app has read/write permission for theme assets.

**Comment by superfein** [comment]
I grabbed a fresh preview_url just for this test, so it can't be that. The private app definitely works because I've been playing around with several different Shopify workflows, like using Gulp for example, and the private app works just fine for other configurations and workflows. The private app is setup correctly I believe, with read/write permission for theme assets. Why would the terminal message say 401 and then Uploaded? Those seem to be contradictory messages.

**Comment by amoser67** [comment]
Gotcha, thanks for the info.  Yea, I guess it does seem kind of weird phrasing wise, might have to change that.  Basically uploaded means upload request has completed, and if it fails the status code is printed.  I will go ahead and play around with the preview url setup, since I haven't tested out that feature very recently.  And just to clarify, your auth env variable follows the api_key:api_pass format right?  I'll assume it does, but if you havent checked might be good just to be safe.

**Comment by amoser67** [comment]
Store preview method seems to be working fine for me, so I will assume it's not specific to that method.

**Comment by superfein** [comment]
Sorry @amoser67 it was my fault! I kept the square brackets in the .env file from your example. Didn't realize I had to remove those. It uploads just fine now. Thanks for all your hard work, I really appreciate it!

**Comment by amoser67** [comment]
Finally one of them was your fault! Lol, I actually did the same thing the
first time I set up theme kit, I will probably just change the docs tbh, I
have always wondered if it would be confusing to others.
