### ISSUE TITLE
JS access is denied error

### ISSUE THREAD

**Issue by superfein** [amoser67/shopify_dev_utils#5]
I'm back! Probably something I'm missing from my side, but I put a file in the `scripts` folder and named it `app.js.liquid` but when I save the file the Node server crashes and I get this error message:
```
C:\Users\Zach Miller\shopify_sites\dev-utils\node_modules\shopify_dev_utils\inde
x.js:195
        if (data === null) throw reason;
                           ^

Error: Command failed: C:\Users\Zach Miller\shopify_sites\dev-utils\node_modules
\shopify_dev_utils\JSMin-master\jsmin.exe <C:\Users\Zach Miller\shopify_sites\de
v-utils\scripts\app.js.liquid >C:\Users\Zach Miller\shopify_sites\dev-utils\them
e\assets\app.min.js.liquid
Access is denied.

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:316:20)
    at maybeClose (internal/child_process.js:1026:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'C:\\Users\\Zach Miller\\shopify_sites\\dev-utils\\node_modules\\shopify_
dev_utils\\JSMin-master\\jsmin.exe <C:\\Users\\Zach Miller\\shopify_sites\\dev-u
tils\\scripts\\app.js.liquid >C:\\Users\\Zach Miller\\shopify_sites\\dev-utils\\
theme\\assets\\app.min.js.liquid'
}
```

What am I missing? Do you know why the access is denied?

**Comment by amoser67** [comment]
The scripts directory expects only .js files not .liquid files.  The error seems kinda weird though.  Can you try removing the liquid extension and see if you get an error?

**Comment by superfein** [comment]
Removed the .liquid extension, still getting the same error message.

Would I still be able to use liquid syntax in my JS without the .liquid extension? Like how you've setup the main.scss file to be renamed to main.scss.liquid, could that be optionally applied to a .js file so that it copies to the assets folder with the .liquid extension? Or do you have a different system for including liquid in your JS?

**Comment by amoser67** [comment]
So there are somethings in the project, this being one, that kind of revolve around my preferences, and how I am used to setting things up.

How I integrate liquid with my JS has two parts.

The first part is with snippets/inline-scripts.  If you create this subdirectory, you can place liquid files in it, where each one should contain a single script tag containing JS and Liquid.  Since there is no additional HTML, we can simply run this file through our JS minifier as if it was a JS file when we upload it.  So basically the local version will remain unminified and then when a change occurs it will copy the file, minify it, and upload it.  As the directory name suggests, the primary purpose of these scripts are to enable an efficient way of using inline scripts.

The second thing I do is I always have one global object I attach to the window, and to initialize this object I have an inline script placed in the head where I save many useful liquid values from the current page as properties of this global object.  This translates liquid values to pure JS values I can use from any of my scripts.


Using a combination of the above two practices, I have never really had a need for using liquid directly in my scripts.  If this seems unsatisfactory, let me know, and I can look into the logistics of adding it.

**Comment by amoser67** [comment]
Regarding the problem, looking into it.

**Comment by amoser67** [comment]
Sorry, got sidetracked with some other stuff.  So I think what is happening is that childProcess.execFile("the_path/jsmin.exe") is being called to execute the jsmin.exe executable file, but the permission to open one of the relevant files is denied.  So we execute jsmin.exe, then read from the scripts\\app.js then write to theme\\assets\\app.js.  So double check the read/write privileges for those three files.

**Comment by superfein** [comment]
I have my Windows User setup in this way: my main user is not the admin, so that every time I install new software or change system settings, or open an exec file, I need to type in the admin password in the popup window. I did this for security reasons, so that if I ever get hacked the attacker can't do much without my admin password. It creates an extra level of security in Windows. The reason I bring this up, is that I wonder if what is happening is the jsmin.exe is trying to run but can't because it needs admin privileges, and that popup window of course doesn't appear because I'm doing this on the command line. 

I tried opening the Git Bash terminal as an admin, then trying to save the app.js file, but I got the same result.

I wasn't sure if the app.js file needed to already exist in the assets folder, so I copied it there and renamed it app.min.js. Same result.

Not entirely sure how to proceed.

**Comment by amoser67** [comment]
So, if you need to be an admin to run any exec file by default, you will have to at least change the permissions of the jsmin exe file. On Unix you use the chmod command, not sure how it is on windows off the top of my head.

**Comment by superfein** [comment]
This is the file permissions on the jsmin.exe file: `-rwxr-xr-x` does that seem right? It turns out it's very difficult to change file permissions in Windows, but if I have to I can look into it further.

There's no simple chmod UNIX method in Windows. 

Tried updating a line of code in `fs_operations.js` to this: `jsmin_path += "-shortcut.exe";` and creating a shortcut to jsmin.exe in the `JSMin-master` folder, naming it `jsmin-shortcut.exe` and forcing it in the shortcut settings to always run as admin. Sadly, that didn't work, got the same error. I thought it might be a sneaky workaround, but no luck.

**Comment by amoser67** [comment]
I think you can just right click any file, go to properties -> security, and it will show you the permissions.  I think that the `-rwxr-xr-x` goes in order of owner, group, others.  r=read,w=write,x=execute.

So for that string, the owner has read write and execute privileges, but the group has no write permission, and others have no read or write permission.  If other files follow this pattern and you do not own them, for example, the theme/assets/app.js file, then you will not be able to write to it.  Can you check the permissions of those?

**Comment by superfein** [comment]
According to the permissions for `app.js` in in the security tab > advanced (I did a deep dive into every permissions section) I am considered the owner and have full control. But in the terminal, the `app.js` file has these permissions: `-rw-r--r--`. In fact, all the files in the theme/assets dir have these same permissions. Yet, the .scss file renamed and copied and minified no problem. This seems strange as it's only affecting the .js file. I really appreciate your help, and I'm sure this is getting annoying for you. I can try to do some digging to see if anyone has had the same issues with a similar Windows user setup.

I also have a laptop where the default user is the admin, I'll do a test there and see if I get different results.

**Comment by superfein** [comment]
Works on my laptop perfectly! I'll have to figure out a way to get it to work on my main work station, thanks again for all your excellent work, support and guidance.

**Comment by amoser67** [comment]
Hey man, thank you, and right back at ya, you found some serious compatibility issues I might never have been aware of otherwise.  I really appreciate all of your help, and please continue to let me know of any issues that you notice, big or small.

Additionally, there is another npm package called jsmin which is a wrapper around an older iteration of the c/c++ version.  I didn't use it because I felt it would be slightly slower, and I don't really want to add it in as a required package, because it's kind of misleading.  That being said, I think what I will do, is add an optional env variable which specifies if you want to use the npm-jsmin fallback, and then provide instructions for installing it.  I think this should allow you to use it on your desktop.
